export const ROLE_USER = "ROLE_USER";

export const ROLE_SUPER_ADMIN = "ROLE_SUPER_ADMIN";

export const ROLE_EXAM_MAKER = "ROLE_EXAM_MAKER";

export const ROLE_ORG_ADMIN = "ROLE_ORG_ADMIN";

export const ROLE_CAMPUS_USER = "ROLE_CAMPUS_USER";

export const PRACTICE_EXAMS = "PRACTICE_EXAMS";

export const ASSIGNED_EXAMS = "ASSIGNED_EXAMS";

export const REPORTS = "REPORTS";

export const MANAGE_EXAMS = "MANAGE_EXAMS";

export const MANAGE_USERS = "MANAGE_USERS";

export const MANAGE_TENANTS = "MANAGE_TENANTS";

export const EXAM_TYPE_PRACTICE = "PRACTICE";

export const EXAM_TYPE_ASSIGNED = "ASSIGNED";

export const EXAM_REPORT = "MY REPORTS";

export const EXAM_TYPE_ALL = "ALL";

export const CONTENT_CREATION = "CONTENT CREATION";

export const QUESTIONS_CREATION = "CREATE QUESTIONS FROM FILE";

export const QUESTION_CREATION = "CREATE QUESTION";

export const ANALYTICS = "ANALYTICS";

export const EXAM_ANALYSIS = "EXAM ANALYSIS";

export const OVERALL_ANALYTICS = "OVRALL ANALYTICS";

export const EXAM_ISFINISHED = "FINISHED";

export const ROLES = [
  ROLE_USER,

  ROLE_SUPER_ADMIN,

  ROLE_EXAM_MAKER,

  ROLE_ORG_ADMIN,

  ROLE_CAMPUS_USER,
];

export const ROLE_BASED_RESOURCES = {
  [ROLE_USER]: [PRACTICE_EXAMS, ASSIGNED_EXAMS, REPORTS],

  [ROLE_SUPER_ADMIN]: [
    MANAGE_EXAMS,
    MANAGE_USERS,
    MANAGE_TENANTS,
    CONTENT_CREATION,
    ANALYTICS,
    OVERALL_ANALYTICS,
  ],

  [ROLE_EXAM_MAKER]: [MANAGE_EXAMS, CONTENT_CREATION],

  [ROLE_CAMPUS_USER]: [ASSIGNED_EXAMS],

  [ROLE_ORG_ADMIN]: [
    MANAGE_USERS,
    MANAGE_TENANTS,
    ANALYTICS,
    OVERALL_ANALYTICS,
  ],
};

export const HOME_ROUTE_PATH = "/home";
